"""add sparring draft to events

Revision ID: 6fd06153e91e
Revises: 7f92d2a57d1a
Create Date: 2026-08-14 10:34:41.157170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6fd06153e91e'
down_revision: Union[str, Sequence[str], None] = '7f92d2a57d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('draft', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'draft')
    # ### end Alembic commands ###
