"""add outcome scores to corpus and embeddings to events

Revision ID: 7f92d2a57d1a
Revises: 3e8dd6ff1ac7
Create Date: 2026-08-14 09:34:03.708433

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f92d2a57d1a"
down_revision: str | Sequence[str] | None = "3e8dd6ff1ac7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prefecture_weight",
        sa.Column("prefecture_id", sa.Integer(), nullable=False),
        sa.Column("regional_weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("prefecture_id"),
    )
    # 既存の12.9万行があるので server_default 無しの NOT NULL は通らない。
    # corpus は load_corpus が TRUNCATE して入れ直すが, migration はそれより先に走る
    op.add_column("corpus", sa.Column("page_view", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("corpus", sa.Column("regional_reach", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("corpus", sa.Column("pv_score", sa.Float(), nullable=False, server_default="0"))
    op.add_column("corpus", sa.Column("regional_score", sa.Float(), nullable=False, server_default="0"))
    op.add_column(
        "events",
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False, server_default="self"),
    )
    op.add_column("events", sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column(
        "events", sa.Column("scored_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="")
    )
    op.add_column("events", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True))
    op.add_column("events", sa.Column("score", sa.Float(), nullable=True))
    op.create_unique_constraint("uq_events_user_external", "events", ["user_id", "external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_events_user_external", "events", type_="unique")
    op.drop_column("events", "score")
    op.drop_column("events", "embedding")
    op.drop_column("events", "scored_text")
    op.drop_column("events", "external_id")
    op.drop_column("events", "source")
    op.drop_column("corpus", "regional_score")
    op.drop_column("corpus", "pv_score")
    op.drop_column("corpus", "regional_reach")
    op.drop_column("corpus", "page_view")
    op.drop_table("prefecture_weight")
    # ### end Alembic commands ###
