"""create corpus tables for pgvector search

Revision ID: edff7774f7c3
Revises:
Create Date: 2026-08-13 16:25:37.063083

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edff7774f7c3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # autogenerate は拡張を検出しない。corpus の VECTOR 列より先に要るので手で足した
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("business_category_id", sa.Integer(), nullable=False),
        sa.Column("business_category_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("business_category_id"),
    )
    op.create_table(
        "corpus",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subtitle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_head", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("business_category_id", sa.Integer(), nullable=True),
        sa.Column("business_category_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_type_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prefecture_id", sa.Integer(), nullable=True),
        sa.Column("prefecture_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_on", sa.Date(), nullable=False),
        sa.Column("reach", sa.Integer(), nullable=False),
        sa.Column("reach_score", sa.Float(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=False),
        sa.PrimaryKeyConstraint("company_id", "release_id"),
    )
    op.create_index(op.f("ix_corpus_business_category_id"), "corpus", ["business_category_id"], unique=False)
    op.create_index(op.f("ix_corpus_prefecture_id"), "corpus", ["prefecture_id"], unique=False)
    op.create_table(
        "corpus_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("new_site_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_corpus_media_company_id"), "corpus_media", ["company_id"], unique=False)
    op.create_index(op.f("ix_corpus_media_new_site_name"), "corpus_media", ["new_site_name"], unique=False)
    op.create_index(op.f("ix_corpus_media_release_id"), "corpus_media", ["release_id"], unique=False)
    op.create_table(
        "media_frequency",
        sa.Column("new_site_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("new_site_name"),
    )
    op.create_table(
        "media_total",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prefecture_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_places_kind"), "places", ["kind"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_places_kind"), table_name="places")
    op.drop_table("places")
    op.drop_table("media_total")
    op.drop_table("media_frequency")
    op.drop_index(op.f("ix_corpus_media_release_id"), table_name="corpus_media")
    op.drop_index(op.f("ix_corpus_media_new_site_name"), table_name="corpus_media")
    op.drop_index(op.f("ix_corpus_media_company_id"), table_name="corpus_media")
    op.drop_table("corpus_media")
    op.drop_index(op.f("ix_corpus_prefecture_id"), table_name="corpus")
    op.drop_index(op.f("ix_corpus_business_category_id"), table_name="corpus")
    op.drop_table("corpus")
    op.drop_table("categories")
    # ### end Alembic commands ###

    # VECTOR 列を持つテーブルを消したあとに落とす
    op.execute("DROP EXTENSION IF EXISTS vector")
